-- Insert TQC conferences
INSERT INTO conferences (venue, year, city, country, country_code, is_virtual, is_hybrid, website_url, proceedings_url, creator, modifier) VALUES
('TQC', 2024, 'Okinawa', 'Japan', 'JP', false, false, 'https://tqc2024.jp', NULL, 'system', 'system'),
('TQC', 2023, 'Aveiro', 'Portugal', 'PT', false, false, 'https://tqc2023.web.ua.pt', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=18033', 'system', 'system'),
('TQC', 2022, 'Illinois', 'United States', 'US', false, false, 'https://tqc2022.web.illinois.edu', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16184', 'system', 'system'),
('TQC', 2021, 'Riga', 'Latvia', 'LV', true, false, 'https://tqc2021.lu.lv', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16183', 'system', 'system'),
('TQC', 2020, 'Riga', 'Latvia', 'LV', true, false, 'https://tqc2020.lu.lv', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16182', 'system', 'system'),
('TQC', 2019, 'Maryland', 'United States', 'US', false, false, 'https://tqc2019.umd.edu', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16181', 'system', 'system'),
('TQC', 2018, 'Sydney', 'Australia', 'AU', false, false, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16180', 'system', 'system'),
('TQC', 2017, 'Paris', 'France', 'FR', false, false, 'https://tqc2017.lip6.fr', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16179', 'system', 'system'),
('TQC', 2016, 'Berlin', 'Germany', 'DE', false, false, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16178', 'system', 'system'),
('TQC', 2015, 'Brussels', 'Belgium', 'BE', false, false, 'https://tqc2015.ulb.ac.be', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16177', 'system', 'system'),
('TQC', 2014, 'Singapore', 'Singapore', 'SG', false, false, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16176', 'system', 'system'),
('TQC', 2013, 'Guelph', 'Canada', 'CA', false, false, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16175', 'system', 'system'),
('TQC', 2012, 'Tokyo', 'Japan', 'JP', false, false, 'https://tqc2012.math.keio.ac.jp', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16174', 'system', 'system'),
('TQC', 2011, 'Madrid', 'Spain', 'ES', false, false, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16173', 'system', 'system'),
('TQC', 2010, 'Leeds', 'United Kingdom', 'GB', false, false, 'https://tqc2010.leeds.ac.uk', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16172', 'system', 'system'),
('TQC', 2009, 'Waterloo', 'Canada', 'CA', false, false, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16171', 'system', 'system'),
('TQC', 2008, 'Tokyo', 'Japan', 'JP', false, false, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16170', 'system', 'system'),
('TQC', 2007, 'Nara', 'Japan', 'JP', false, false, NULL, NULL, 'system', 'system'),
('TQC', 2006, 'Kanagawa', 'Japan', 'JP', false, false, NULL, NULL, 'system', 'system'); 