-- Insert QIP conferences
INSERT INTO conferences (venue, year, city, country, country_code, is_virtual, is_hybrid, venue_name, website_url, creator, modifier) VALUES
('QIP', 2024, 'Taipei', 'Taiwan', 'TW', false, false, 'NTU/CYCU/NCKU/NSYSU/NYCU/NTHU', 'https://qipconference.org/2024/', 'system', 'system'),
('QIP', 2023, 'Ghent', 'Belgium', 'BE', false, false, 'UGhent', 'https://qipconference.org/2023/', 'system', 'system'),
('QIP', 2022, 'Pasadena', 'United States', 'US', false, false, 'Caltech', 'https://qipconference.org/2022/', 'system', 'system'),
('QIP', 2021, 'Munich', 'Germany', 'DE', true, false, 'TU Munich', 'https://qipconference.org/2021/', 'system', 'system'),
('QIP', 2020, 'Shenzhen', 'China', 'CN', false, false, 'SUSTech and Peng Cheng Laboratory', 'https://qipconference.org/2020/', 'system', 'system'),
('QIP', 2019, 'Boulder', 'United States', 'US', false, false, 'CU Boulder', 'https://qipconference.org/2019/', 'system', 'system'),
('QIP', 2018, 'Delft', 'Netherlands', 'NL', false, false, 'TU Delft', 'https://qipconference.org/2018/', 'system', 'system'),
('QIP', 2017, 'Seattle', 'United States', 'US', false, false, 'MSR', 'https://qipconference.org/2017/', 'system', 'system'),
('QIP', 2016, 'Banff', 'Canada', 'CA', false, false, 'UCalgary', 'https://qipconference.org/2016/', 'system', 'system'),
('QIP', 2015, 'Sydney', 'Australia', 'AU', false, false, 'UTS', 'https://qipconference.org/2015/', 'system', 'system'),
('QIP', 2014, 'Barcelona', 'Spain', 'ES', false, false, 'UB/UAB/ICFO', 'https://qipconference.org/2014/', 'system', 'system'),
('QIP', 2013, 'Beijing', 'China', 'CN', false, false, 'Tsinghua University', 'https://qipconference.org/2013/', 'system', 'system'),
('QIP', 2012, 'Montreal', 'Canada', 'CA', false, false, 'UdeM', 'https://qipconference.org/2012/', 'system', 'system'),
('QIP', 2011, 'Singapore', 'Singapore', 'SG', false, false, 'NUS', 'https://qipconference.org/2011/', 'system', 'system'),
('QIP', 2010, 'Zurich', 'Switzerland', 'CH', false, false, 'ETHZ', 'https://qipconference.org/2010/', 'system', 'system'),
('QIP', 2009, 'Santa Fe', 'United States', 'US', false, false, 'UNM/SFI/LANL', 'https://qipconference.org/2009/', 'system', 'system'),
('QIP', 2008, 'New Delhi', 'India', 'IN', false, false, 'IIT/TIFR', 'https://qipconference.org/2008/', 'system', 'system'),
('QIP', 2007, 'Brisbane', 'Australia', 'AU', false, false, 'UQ', 'https://qipconference.org/2007/', 'system', 'system'),
('QIP', 2006, 'Paris', 'France', 'FR', false, false, 'University Paris-Sud', 'https://qipconference.org/2006/', 'system', 'system'),
('QIP', 2005, 'Cambridge', 'United States', 'US', false, false, 'MIT', 'https://qipconference.org/2005/', 'system', 'system'),
('QIP', 2004, 'Waterloo', 'Canada', 'CA', false, false, 'PI/IQC', 'https://qipconference.org/2004/', 'system', 'system'),
('QIP', 2003, 'Berkeley', 'United States', 'US', false, false, 'MSRI', 'https://qipconference.org/2003/', 'system', 'system'),
('QIP', 2002, 'Yorktown Heights', 'United States', 'US', false, false, 'IBM', 'https://qipconference.org/2002/', 'system', 'system'),
('QIP', 2001, 'Amsterdam', 'Netherlands', 'NL', false, false, 'CWI', 'https://qipconference.org/2001/', 'system', 'system'),
('QIP', 2000, 'Montreal', 'Canada', 'CA', false, false, 'CRM', 'https://qipconference.org/2000/', 'system', 'system'),
('QIP', 1999, 'Chicago', 'United States', 'US', false, false, 'DePaul University', 'https://qipconference.org/1999/', 'system', 'system'),
('QIP', 1998, 'Aarhus', 'Denmark', 'DK', false, false, 'AU', 'https://qipconference.org/1998/', 'system', 'system'); 