-- Insert QCRYPT conferences
INSERT INTO conferences (venue, year, city, country, country_code, is_virtual, is_hybrid, venue_name, website_url,
    archive_url, archive_organizers_url, archive_pc_url, archive_steering_url, archive_program_url,
    creator, modifier) VALUES
('QCRYPT', 2024, 'Vigo', 'Spain', 'ES', false, false, NULL, 'https://2024.qcrypt.net',
    'https://qcrypt.iaqi.org/2024/',
    'https://qcrypt.iaqi.org/2024/team/index.html',
    'https://qcrypt.iaqi.org/2024/team/index.html',
    'https://qcrypt.iaqi.org/2024/team/index.html',
    'https://qcrypt.iaqi.org/2024/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2023, 'Maryland', 'United States', 'US', false, false, NULL, 'https://2023.qcrypt.net',
    'https://qcrypt.iaqi.org/2023/',
    'https://qcrypt.iaqi.org/2023/team/index.html',
    'https://qcrypt.iaqi.org/2023/team/index.html',
    'https://qcrypt.iaqi.org/2023/team/index.html',
    'https://qcrypt.iaqi.org/2023/schedule.html',
    'system', 'system'),
('QCRYPT', 2022, 'Taipei', 'Taiwan', 'TW', false, false, NULL, 'https://2022.qcrypt.net',
    'https://qcrypt.iaqi.org/2022/',
    'https://qcrypt.iaqi.org/2022/team/index.html',
    'https://qcrypt.iaqi.org/2022/team/index.html',
    'https://qcrypt.iaqi.org/2022/team/index.html',
    'https://qcrypt.iaqi.org/2022/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2021, 'Amsterdam', 'Netherlands', 'NL', true, false, NULL, 'https://2021.qcrypt.net',
    'https://qcrypt.iaqi.org/2021/',
    'https://qcrypt.iaqi.org/2021/team/index.html',
    'https://qcrypt.iaqi.org/2021/team/index.html',
    'https://qcrypt.iaqi.org/2021/team/index.html',
    'https://qcrypt.iaqi.org/2021/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2020, 'Amsterdam', 'Netherlands', 'NL', true, false, NULL, 'https://2020.qcrypt.net',
    'https://qcrypt.iaqi.org/2020/',
    'https://qcrypt.iaqi.org/2020/team/index.html',
    'https://qcrypt.iaqi.org/2020/team/index.html',
    'https://qcrypt.iaqi.org/2020/team/index.html',
    'https://qcrypt.iaqi.org/2020/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2019, 'Montreal', 'Canada', 'CA', false, false, NULL, 'https://qcrypt.github.io/2019.qcrypt.net/index.html',
    'https://qcrypt.iaqi.org/2019/',
    'https://qcrypt.iaqi.org/2019/team/index.html',
    'https://qcrypt.iaqi.org/2019/team/index.html',
    'https://qcrypt.iaqi.org/2019/team/index.html',
    'https://qcrypt.iaqi.org/2019/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2018, 'Shanghai', 'China', 'CN', false, false, NULL, 'https://qcrypt.github.io/2018.qcrypt.net/index.html',
    'https://qcrypt.iaqi.org/2018/',
    'https://qcrypt.iaqi.org/2018/team/index.html',
    'https://qcrypt.iaqi.org/2018/team/index.html',
    'https://qcrypt.iaqi.org/2018/team/index.html',
    'https://qcrypt.iaqi.org/2018/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2017, 'Cambridge', 'United Kingdom', 'GB', false, false, NULL, 'https://qcrypt.github.io/2017.qcrypt.net/index.html',
    'https://qcrypt.iaqi.org/2017/',
    'https://qcrypt.iaqi.org/2017/team/index.html',
    'https://qcrypt.iaqi.org/2017/team/index.html',
    'https://qcrypt.iaqi.org/2017/team/index.html',
    'https://qcrypt.iaqi.org/2017/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2016, 'Washington', 'United States', 'US', false, false, NULL, 'https://qcrypt.github.io/2016.qcrypt.net/index.html',
    'https://qcrypt.iaqi.org/2016/',
    'https://qcrypt.iaqi.org/2016/team/index.html',
    'https://qcrypt.iaqi.org/2016/team/index.html',
    'https://qcrypt.iaqi.org/2016/team/index.html',
    'https://qcrypt.iaqi.org/2016/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2015, 'Tokyo', 'Japan', 'JP', false, false, NULL, 'https://qcrypt.github.io/2015.qcrypt.net/index.html%3Fp=25.html',
    'https://qcrypt.iaqi.org/2015/',
    'https://qcrypt.iaqi.org/2015/team/index.html',
    'https://qcrypt.iaqi.org/2015/team/index.html',
    'https://qcrypt.iaqi.org/2015/team/index.html',
    'https://qcrypt.iaqi.org/2015/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2014, 'Paris', 'France', 'FR', false, false, NULL, 'https://qcrypt.github.io/2014.qcrypt.net/index.html',
    'https://qcrypt.iaqi.org/2014/',
    'https://qcrypt.iaqi.org/2014/team/index.html',
    'https://qcrypt.iaqi.org/2014/team/index.html',
    'https://qcrypt.iaqi.org/2014/team/index.html',
    'https://qcrypt.iaqi.org/2014/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2013, 'Waterloo', 'Canada', 'CA', false, false, NULL, 'https://qcrypt.github.io/2013.qcrypt.net/index.html',
    'https://qcrypt.iaqi.org/2013/',
    'https://qcrypt.iaqi.org/2013/team/index.html',
    'https://qcrypt.iaqi.org/2013/team/index.html',
    'https://qcrypt.iaqi.org/2013/team/index.html',
    'https://qcrypt.iaqi.org/2013/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2012, 'Singapore', 'Singapore', 'SG', false, false, NULL, 'https://qcrypt.github.io/2012.qcrypt.net/index.html',
    'https://qcrypt.iaqi.org/2012/',
    'https://qcrypt.iaqi.org/2012/team/index.html',
    'https://qcrypt.iaqi.org/2012/team/index.html',
    'https://qcrypt.iaqi.org/2012/team/index.html',
    'https://qcrypt.iaqi.org/2012/schedule/index.html',
    'system', 'system'),
('QCRYPT', 2011, 'Zurich', 'Switzerland', 'CH', false, false, NULL, 'https://qcrypt.github.io/2011.qcrypt.net/index.html',
    'https://qcrypt.iaqi.org/2011/',
    'https://qcrypt.iaqi.org/2011/team/index.html',
    'https://qcrypt.iaqi.org/2011/team/index.html',
    'https://qcrypt.iaqi.org/2011/team/index.html',
    'https://qcrypt.iaqi.org/2011/schedule/index.html',
    'system', 'system')
ON CONFLICT (venue, year) DO UPDATE SET
    archive_url = EXCLUDED.archive_url,
    archive_organizers_url = EXCLUDED.archive_organizers_url,
    archive_pc_url = EXCLUDED.archive_pc_url,
    archive_steering_url = EXCLUDED.archive_steering_url,
    archive_program_url = EXCLUDED.archive_program_url,
    updated_at = NOW();
