-- Insert QIP conferences
INSERT INTO conferences (venue, year, city, country, country_code, is_virtual, is_hybrid, venue_name, website_url,
    archive_url, archive_organizers_url, archive_pc_url, archive_steering_url, archive_program_url,
    creator, modifier) VALUES
('QIP', 2024, 'Taipei', 'Taiwan', 'TW', false, false, 'NTU/CYCU/NCKU/NSYSU/NYCU/NTHU', 'https://qipconference.org/2024/',
    'https://qip.iaqi.org/2024/',
    'https://qip.iaqi.org/2024/site/mypage.aspx?pid=239&lang=en&sid=1522.html',
    'https://qip.iaqi.org/2024/site/mypage.aspx?pid=254&lang=en&sid=1522.html',
    'https://qip.iaqi.org/2024/site/mypage.aspx?pid=238&lang=en&sid=1522.html',
    'https://qip.iaqi.org/2024/site/mypage.aspx?pid=261&lang=en&sid=1522.html',
    'system', 'system'),
('QIP', 2023, 'Ghent', 'Belgium', 'BE', false, false, 'UGhent', 'https://qipconference.org/2023/',
    'https://qip.iaqi.org/2023/',
    'https://qip.iaqi.org/2023/page/26158-local-organising-committee.html',
    'https://qip.iaqi.org/2023/page/26159-program-committee.html',
    'https://qip.iaqi.org/2023/page/26274-steering-committee.html',
    'https://qip.iaqi.org/2023/timetable/index.html',
    'system', 'system'),
('QIP', 2022, 'Pasadena', 'United States', 'US', false, false, 'Caltech', 'https://qipconference.org/2022/',
    'https://qip.iaqi.org/2022/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2021, 'Munich', 'Germany', 'DE', true, false, 'TU Munich', 'https://qipconference.org/2021/',
    'https://qip.iaqi.org/2021/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2020, 'Shenzhen', 'China', 'CN', false, false, 'SUSTech and Peng Cheng Laboratory', 'https://qipconference.org/2020/',
    'https://qip.iaqi.org/2020/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2019, 'Boulder', 'United States', 'US', false, false, 'CU Boulder', 'https://qipconference.org/2019/',
    'https://qip.iaqi.org/2019/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2018, 'Delft', 'Netherlands', 'NL', false, false, 'TU Delft', 'https://qipconference.org/2018/',
    'https://qip.iaqi.org/2018/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2017, 'Seattle', 'United States', 'US', false, false, 'MSR', 'https://qipconference.org/2017/',
    'https://qip.iaqi.org/2017/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2016, 'Banff', 'Canada', 'CA', false, false, 'UCalgary', 'https://qipconference.org/2016/',
    'https://qip.iaqi.org/2016/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2015, 'Sydney', 'Australia', 'AU', false, false, 'UTS', 'https://qipconference.org/2015/',
    'https://qip.iaqi.org/2015/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2014, 'Barcelona', 'Spain', 'ES', false, false, 'UB/UAB/ICFO', 'https://qipconference.org/2014/',
    'https://qip.iaqi.org/2014/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2013, 'Beijing', 'China', 'CN', false, false, 'Tsinghua University', 'https://qipconference.org/2013/',
    'https://qip.iaqi.org/2013/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2012, 'Montreal', 'Canada', 'CA', false, false, 'UdeM', 'https://qipconference.org/2012/',
    'https://qip.iaqi.org/2012/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2011, 'Singapore', 'Singapore', 'SG', false, false, 'NUS', 'https://qipconference.org/2011/',
    'https://qip.iaqi.org/2011/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2010, 'Zurich', 'Switzerland', 'CH', false, false, 'ETHZ', 'https://qipconference.org/2010/',
    'https://qip.iaqi.org/2010/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2009, 'Santa Fe', 'United States', 'US', false, false, 'UNM/SFI/LANL', 'https://qipconference.org/2009/',
    'https://qip.iaqi.org/2009/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2008, 'New Delhi', 'India', 'IN', false, false, 'IIT/TIFR', 'https://qipconference.org/2008/',
    'https://qip.iaqi.org/2008/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2007, 'Brisbane', 'Australia', 'AU', false, false, 'UQ', 'https://qipconference.org/2007/',
    'https://qip.iaqi.org/2007/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2006, 'Paris', 'France', 'FR', false, false, 'University Paris-Sud', 'https://qipconference.org/2006/',
    'https://qip.iaqi.org/2006/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2005, 'Cambridge', 'United States', 'US', false, false, 'MIT', 'https://qipconference.org/2005/',
    'https://qip.iaqi.org/2005/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2004, 'Waterloo', 'Canada', 'CA', false, false, 'PI/IQC', 'https://qipconference.org/2004/',
    'https://qip.iaqi.org/2004/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2003, 'Berkeley', 'United States', 'US', false, false, 'MSRI', 'https://qipconference.org/2003/',
    'https://qip.iaqi.org/2003/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2002, 'Yorktown Heights', 'United States', 'US', false, false, 'IBM', 'https://qipconference.org/2002/',
    'https://qip.iaqi.org/2002/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2001, 'Amsterdam', 'Netherlands', 'NL', false, false, 'CWI', 'https://qipconference.org/2001/',
    'https://qip.iaqi.org/2001/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 2000, 'Montreal', 'Canada', 'CA', false, false, 'CRM', 'https://qipconference.org/2000/',
    'https://qip.iaqi.org/2000/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 1999, 'Chicago', 'United States', 'US', false, false, 'DePaul University', 'https://qipconference.org/1999/',
    'https://qip.iaqi.org/1999/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('QIP', 1998, 'Aarhus', 'Denmark', 'DK', false, false, 'AU', 'https://qipconference.org/1998/',
    'https://qip.iaqi.org/1998/',
    NULL, NULL, NULL, NULL,
    'system', 'system')
ON CONFLICT (venue, year) DO UPDATE SET
    archive_url = EXCLUDED.archive_url,
    archive_organizers_url = EXCLUDED.archive_organizers_url,
    archive_pc_url = EXCLUDED.archive_pc_url,
    archive_steering_url = EXCLUDED.archive_steering_url,
    archive_program_url = EXCLUDED.archive_program_url,
    updated_at = NOW();
