-- Insert QIP conferences
--
-- website_url  = the organisers' original conference site (a Web Archive
--                snapshot when the original domain is offline), matching the
--                curated "original website" column on https://qip.iaqi.org/previousqips
-- archive_url  = the IAQI static copy (https://qip.iaqi.org/<year>/), or NULL
--                when no local mirror exists (2022).
INSERT INTO conferences (venue, year, city, country, country_code, is_virtual, is_hybrid, venue_name, website_url,
    archive_url, archive_organizers_url, archive_pc_url, archive_steering_url, archive_program_url,
    creator, modifier) VALUES
('QIP', 2026, 'Riga', 'Latvia', 'LV', false, false, 'University of Latvia', 'https://qip2026.lu.lv',
    'https://qip.iaqi.org/2026/',
    'https://qip.iaqi.org/2026/about/local-organizing-team/',
    'https://qip.iaqi.org/2026/about/programme-committee/',
    'https://qip.iaqi.org/2026/about/steering-committee/',
    'https://qip.iaqi.org/2026/programme/accepted-papers/',
    'system', 'system'),
('QIP', 2025, 'Raleigh', 'United States', 'US', false, false, 'Duke, NC State', 'https://qip2025.duke.edu',
    'https://qip.iaqi.org/2025/',
NULL, NULL, NULL,
    'https://qip.iaqi.org/2025/accepted-talks/index.html',
    'system', 'system'),
('QIP', 2024, 'Taipei', 'Taiwan', 'TW', false, false, 'NTU/CYCU/NCKU/NSYSU/NYCU/NTHU', 'https://web.archive.org/web/20231204140056/https://qip2024.tw/site/mypage.aspx?lang=en&pid=259&sid=1522',
    'https://qip.iaqi.org/2024/',
    'https://qip.iaqi.org/2024/site/mypage.aspx?pid=239&lang=en&sid=1522.html',
    'https://qip.iaqi.org/2024/site/mypage.aspx?pid=254&lang=en&sid=1522.html',
    'https://qip.iaqi.org/2024/site/mypage.aspx?pid=238&lang=en&sid=1522.html',
    'https://qip.iaqi.org/2024/site/mypage.aspx?pid=261&lang=en&sid=1522.html',
    'system', 'system'),
-- 2023: Indico-based site; all committee pages under event/13076/page/
('QIP', 2023, 'Ghent', 'Belgium', 'BE', false, false, 'UGhent', 'https://indico.cern.ch/event/1175020/',
    'https://qip.iaqi.org/2023/',
    'https://qip.iaqi.org/2023/event/13076/page/3879-local-organising-committee.html',
    'https://qip.iaqi.org/2023/event/13076/page/3880-program-committee.html',
    'https://qip.iaqi.org/2023/event/13076/page/3885-steering-committee.html',
    'https://qip.iaqi.org/2023/event/13076/timetable/index.html',
    'system', 'system'),
-- 2022: No local archive copy; committee data was collected manually
('QIP', 2022, 'Pasadena', 'United States', 'US', false, false, 'Caltech', 'https://cvent.me/QrzQvQ',
    NULL,
    NULL, NULL, NULL, NULL,
    'system', 'system'),
-- 2021: Combined committee page (OC + PC + SC all on one page)
('QIP', 2021, 'Munich', 'Germany', 'DE', true, false, 'TU Munich', 'https://www.mcqst.de/qip2021/',
    'https://qip.iaqi.org/2021/',
    'https://qip.iaqi.org/2021/qip2021/program/committees/',
    'https://qip.iaqi.org/2021/qip2021/program/committees/',
    'https://qip.iaqi.org/2021/qip2021/program/committees/',
    'https://qip.iaqi.org/2021/qip2021/program/conference-program/',
    'system', 'system'),
-- 2020: SPA (JS bundle only), no committee pages in local archive
('QIP', 2020, 'Shenzhen', 'China', 'CN', false, false, 'SUSTech and Peng Cheng Laboratory', 'https://web.archive.org/web/20200630014352/http://www.szpclab.com/qip2020',
    'https://qip.iaqi.org/2020/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
-- 2019: OC on local.html, PC+SC on about.html (sections #pc and #steering)
('QIP', 2019, 'Boulder', 'United States', 'US', false, false, 'CU Boulder', 'https://jila.colorado.edu/qip2019/',
    'https://qip.iaqi.org/2019/',
    'https://qip.iaqi.org/2019/local.html',
    'https://qip.iaqi.org/2019/about.html',
    'https://qip.iaqi.org/2019/about.html',
    'https://qip.iaqi.org/2019/program.html',
    'system', 'system'),
-- 2018: All committees on a single aboutqip page
('QIP', 2018, 'Delft', 'Netherlands', 'NL', false, false, 'TU Delft', 'http://web.archive.org/web/20180819102116/https://qutech.nl/qip2018/',
    'https://qip.iaqi.org/2018/',
    'https://qip.iaqi.org/2018/qutech.nl/qip2018/aboutqip/index.html',
    'https://qip.iaqi.org/2018/qutech.nl/qip2018/aboutqip/index.html',
    'https://qip.iaqi.org/2018/qutech.nl/qip2018/aboutqip/index.html',
    'https://qip.iaqi.org/2018/qutech.nl/qip2018/qip-2018-program-details/index.html',
    'system', 'system'),
-- 2017: SPA; all content embedded in index.html, no separate committee pages
('QIP', 2017, 'Seattle', 'United States', 'US', false, false, 'MSR', 'https://www.microsoft.com/en-us/research/event/qip-2017/',
    'https://qip.iaqi.org/2017/',
    'https://qip.iaqi.org/2017/index.html',
    'https://qip.iaqi.org/2017/index.html',
    'https://qip.iaqi.org/2017/index.html',
    'https://qip.iaqi.org/2017/index.html',
    'system', 'system'),
('QIP', 2016, 'Banff', 'Canada', 'CA', false, false, 'UCalgary', 'https://www.ucalgary.ca/qip2016/',
    'https://qip.iaqi.org/2016/',
    'https://qip.iaqi.org/2016/committees.html',
    'https://qip.iaqi.org/2016/committees.html',
    'https://qip.iaqi.org/2016/committees.html',
    'https://qip.iaqi.org/2016/accepted-talks.html',
    'system', 'system'),
('QIP', 2015, 'Sydney', 'Australia', 'AU', false, false, 'UTS', 'http://web.archive.org/web/20150223074611/http://quantum-lab.org/qip2015/index.php',
    'https://qip.iaqi.org/2015/',
    'https://qip.iaqi.org/2015/Committees.php.html',
    'https://qip.iaqi.org/2015/Committees.php.html',
    'https://qip.iaqi.org/2015/Committees.php.html',
    'https://qip.iaqi.org/2015/Program.php.html',
    'system', 'system'),
('QIP', 2014, 'Barcelona', 'Spain', 'ES', false, false, 'UB/UAB/ICFO', 'https://benasque.org/2014QIP/',
    'https://qip.iaqi.org/2014/',
    'https://qip.iaqi.org/2014/cgi-bin/committees.pl.html',
    'https://qip.iaqi.org/2014/cgi-bin/committees.pl.html',
    'https://qip.iaqi.org/2014/cgi-bin/committees.pl.html',
    'https://qip.iaqi.org/2014/cgi-bin/program.pl.html',
    'system', 'system'),
('QIP', 2013, 'Beijing', 'China', 'CN', false, false, 'Tsinghua University', 'https://conference.iiis.tsinghua.edu.cn/QIP2013/',
    'https://qip.iaqi.org/2013/',
    'https://qip.iaqi.org/2013/index.html@p=8.html',
    'https://qip.iaqi.org/2013/index.html@p=8.html',
    'https://qip.iaqi.org/2013/index.html@p=8.html',
    'https://qip.iaqi.org/2013/index.html@p=6.html',
    'system', 'system'),
('QIP', 2012, 'Montreal', 'Canada', 'CA', false, false, 'UdeM', 'http://web.archive.org/web/20160325192759/http://www.crm.umontreal.ca/QIP2012/index_e.php',
    'https://qip.iaqi.org/2012/',
    'https://qip.iaqi.org/2012/committee_e.php.html',
    'https://qip.iaqi.org/2012/committee_e.php.html',
    'https://qip.iaqi.org/2012/committee_e.php.html',
    'https://qip.iaqi.org/2012/scientific_e.php.html',
    'system', 'system'),
('QIP', 2011, 'Singapore', 'Singapore', 'SG', false, false, 'NUS', 'http://web.archive.org/web/20110727192819/http://qip2011.quantumlah.org/',
    'https://qip.iaqi.org/2011/',
    'https://qip.iaqi.org/2011/committees/',
    'https://qip.iaqi.org/2011/committees/',
    'https://qip.iaqi.org/2011/committees/',
    'https://qip.iaqi.org/2011/scientificprogramme/',
    'system', 'system'),
('QIP', 2010, 'Zurich', 'Switzerland', 'CH', false, false, 'ETHZ', 'http://web.archive.org/web/20091213172202/http://www.qip2010.ethz.ch/',
    'https://qip.iaqi.org/2010/',
    'https://qip.iaqi.org/2010/committee.html',
    'https://qip.iaqi.org/2010/committee.html',
    'https://qip.iaqi.org/2010/committee.html',
    'https://qip.iaqi.org/2010/programme.html',
    'system', 'system'),
('QIP', 2009, 'Santa Fe', 'United States', 'US', false, false, 'UNM/SFI/LANL', 'http://web.archive.org/web/20100415000851/http://info.phys.unm.edu/qip2009/',
    'https://qip.iaqi.org/2009/',
    'https://qip.iaqi.org/2009/organizing-committees.html',
    'https://qip.iaqi.org/2009/organizing-committees.html',
    'https://qip.iaqi.org/2009/organizing-committees.html',
    'https://qip.iaqi.org/2009/talks.html',
    'system', 'system'),
-- 2008: All committees listed in the main index.html
('QIP', 2008, 'New Delhi', 'India', 'IN', false, false, 'IIT/TIFR', 'http://web.archive.org/web/20080812061449/http://www.iarcs.org.in/events/fsttcs07-qip08.php',
    'https://qip.iaqi.org/2008/',
    'https://qip.iaqi.org/2008/index.html',
    'https://qip.iaqi.org/2008/index.html',
    'https://qip.iaqi.org/2008/index.html',
    'https://qip.iaqi.org/2008/Program.html',
    'system', 'system'),
-- 2007: Committees embedded in index.htm; no separate committee page
('QIP', 2007, 'Brisbane', 'Australia', 'AU', false, false, 'UQ', 'http://web.archive.org/web/20060820193320/http://www.qinfo.org/qip/',
    'https://qip.iaqi.org/2007/',
    'https://qip.iaqi.org/2007/index.htm',
    'https://qip.iaqi.org/2007/index.htm',
    'https://qip.iaqi.org/2007/index.htm',
    'https://qip.iaqi.org/2007/program.htm',
    'system', 'system'),
-- 2006: Committees embedded in index.html; accepted talks used as program page
('QIP', 2006, 'Paris', 'France', 'FR', false, false, 'University Paris-Sud', 'http://web.archive.org/web/20051016054631/http://www.lri.fr/qip06/',
    'https://qip.iaqi.org/2006/',
    'https://qip.iaqi.org/2006/index.html',
    'https://qip.iaqi.org/2006/index.html',
    'https://qip.iaqi.org/2006/index.html',
    'https://qip.iaqi.org/2006/accepted_talks.html',
    'system', 'system'),
-- 2005: No committee page in archive
('QIP', 2005, 'Cambridge', 'United States', 'US', false, false, 'MIT', 'http://web.mit.edu/qip2005',
    'https://qip.iaqi.org/2005/',
    NULL, NULL, NULL,
    'https://qip.iaqi.org/2005/schedule.shtml.html',
    'system', 'system'),
-- 2004: No committee page in archive
('QIP', 2004, 'Waterloo', 'Canada', 'CA', false, false, 'PI/IQC', 'https://web.archive.org/web/20130513201229/http://www.iqc.ca:80/conferences/qip/details.html',
    'https://qip.iaqi.org/2004/',
    NULL, NULL, NULL,
    'https://qip.iaqi.org/2004/schedule.html',
    'system', 'system'),
-- 2003: No committee page in archive
('QIP', 2003, 'Berkeley', 'United States', 'US', false, false, 'MSRI', 'https://www.slmath.org/workshops/204',
    'https://qip.iaqi.org/2003/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
-- 2002: OC only (organizers hardcoded from index.html); no PC/SC page archived
('QIP', 2002, 'Yorktown Heights', 'United States', 'US', false, false, 'IBM', 'https://web.archive.org/web/20110604210434/http://www.research.ibm.com/quantuminfo/qip2002/',
    'https://qip.iaqi.org/2002/',
    'https://qip.iaqi.org/2002/index.html',
    NULL, NULL,
    'https://qip.iaqi.org/2002/Schedule.html',
    'system', 'system'),
-- 2001: OC only (organizers hardcoded from index.html); no PC/SC page archived
('QIP', 2001, 'Amsterdam', 'Netherlands', 'NL', false, false, 'CWI', 'https://homepages.cwi.nl/~qip/',
    'https://qip.iaqi.org/2001/',
    'https://qip.iaqi.org/2001/index.html',
    NULL, NULL,
    'https://qip.iaqi.org/2001/program.html',
    'system', 'system'),
-- 2000: OC only (organizers from index.html); no schedule page identified
('QIP', 2000, 'Montreal', 'Canada', 'CA', false, false, 'CRM', 'https://web.archive.org/web/19990829195534/http://www.crm.umontreal.ca:80/act/theme/1999/at_1999_12_05_an.html',
    'https://qip.iaqi.org/2000/',
    'https://qip.iaqi.org/2000/index.html',
    NULL, NULL,
    'https://qip.iaqi.org/2000/at_1999_12_05_sch.html',
    'system', 'system'),
-- 1999: Organizers and PC on theme.htm; program page separate
('QIP', 1999, 'Chicago', 'United States', 'US', false, false, 'DePaul University', 'https://web.archive.org/web/20000412153350/http://aqip.cs.depaul.edu:80/AQIP/Default.htm',
    'https://qip.iaqi.org/1999/',
    'https://qip.iaqi.org/1999/theme.htm',
    'https://qip.iaqi.org/1999/theme.htm',
    NULL,
    'https://qip.iaqi.org/1999/program.htm',
    'system', 'system'),
-- 1998: Committees on prog.html (PC chair + OC); schedule on program.html
('QIP', 1998, 'Aarhus', 'Denmark', 'DK', false, false, 'AU', 'https://web.archive.org/web/20100422225206/http://www.brics.dk:80/Activities/98/aqip/',
    'https://qip.iaqi.org/1998/',
    'https://qip.iaqi.org/1998/prog.html',
    'https://qip.iaqi.org/1998/prog.html',
    NULL,
    'https://qip.iaqi.org/1998/program.html',
    'system', 'system')
ON CONFLICT (venue, year) DO UPDATE SET
    website_url = EXCLUDED.website_url,
    archive_url = EXCLUDED.archive_url,
    archive_organizers_url = EXCLUDED.archive_organizers_url,
    archive_pc_url = EXCLUDED.archive_pc_url,
    archive_steering_url = EXCLUDED.archive_steering_url,
    archive_program_url = EXCLUDED.archive_program_url,
    updated_at = NOW();
