-- Insert TQC conferences
INSERT INTO conferences (venue, year, city, country, country_code, is_virtual, is_hybrid, venue_name, website_url, proceedings_url,
    archive_url, archive_organizers_url, archive_pc_url, archive_steering_url, archive_program_url,
    creator, modifier) VALUES
('TQC', 2026, 'Sherbrooke', 'Canada', 'CA', false, false, 'Université de Sherbrooke', 'https://tqc-conference.org/2026/', NULL,
    'https://tqc.iaqi.org/2026/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2025, 'Bengaluru', 'India', 'IN', false, false, NULL, 'https://fs3x4avdgq.preview.infomaniak.website/', NULL,
    'https://tqc.iaqi.org/2025/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2024, 'Okinawa', 'Japan', 'JP', false, false, 'OIST', 'https://fs3x4avdgq.preview.infomaniak.website/tqc-2024', NULL,
    'https://tqc.iaqi.org/2025/tqc-2024/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2023, 'Aveiro', 'Portugal', 'PT', false, false, 'Universidade de Aveiro', 'https://tqc2023.web.ua.pt', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=18033',
    'https://tqc.iaqi.org/2025/tqc2023/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2022, 'Illinois', 'United States', 'US', false, false, 'University of Illinois Urbana-Champaign', 'https://tqc2022.web.illinois.edu', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16184',
    'https://tqc.iaqi.org/2022/',
    'https://tqc.iaqi.org/2022/people/index.html',
    'https://tqc.iaqi.org/2022/people/index.html',
    'https://tqc.iaqi.org/2022/people/index.html',
    'https://tqc.iaqi.org/2022/program/index.html',
    'system', 'system'),
('TQC', 2021, 'Riga', 'Latvia', 'LV', true, false, 'University of Latvia', 'https://tqc2021.lu.lv', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16183',
    'https://tqc.iaqi.org/2021/',
    'https://tqc.iaqi.org/2021/people/',
    'https://tqc.iaqi.org/2021/people/',
    'https://tqc.iaqi.org/2021/people/',
    'https://tqc.iaqi.org/2021/program/schedule/',
    'system', 'system'),
('TQC', 2020, 'Riga', 'Latvia', 'LV', true, false, 'University of Latvia', 'https://tqc2020.lu.lv', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16182',
    'https://tqc.iaqi.org/2020/',
    'https://tqc.iaqi.org/2020/people/',
    'https://tqc.iaqi.org/2020/people/',
    'https://tqc.iaqi.org/2020/people/',
    'https://tqc.iaqi.org/2020/program/schedule/',
    'system', 'system'),
('TQC', 2019, 'Maryland', 'United States', 'US', false, false, 'University of Maryland', 'https://tqc2019.umd.edu', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16181',
    'https://tqc.iaqi.org/2019/',
    'https://tqc.iaqi.org/2019/committees/index.html',
    'https://tqc.iaqi.org/2019/committees/index.html',
    'https://tqc.iaqi.org/2019/committees/index.html',
    'https://tqc.iaqi.org/2019/schedule/index.html',
    'system', 'system'),
('TQC', 2018, 'Sydney', 'Australia', 'AU', false, false, NULL, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16180',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2017, 'Paris', 'France', 'FR', false, false, 'LIP6', 'https://tqc2017.lip6.fr', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16179',
    'https://tqc.iaqi.org/2017/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2016, 'Berlin', 'Germany', 'DE', false, false, NULL, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16178',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2015, 'Brussels', 'Belgium', 'BE', false, false, 'ULB', 'https://tqc2015.ulb.ac.be', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16177',
    'https://tqc.iaqi.org/2015/',
    NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2014, 'Singapore', 'Singapore', 'SG', false, false, NULL, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16176',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2013, 'Guelph', 'Canada', 'CA', false, false, NULL, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16175',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2012, 'Tokyo', 'Japan', 'JP', false, false, 'Keio University', 'https://tqc2012.math.keio.ac.jp', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16174',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2011, 'Madrid', 'Spain', 'ES', false, false, NULL, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16173',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2010, 'Leeds', 'United Kingdom', 'GB', false, false, 'University of Leeds', 'https://tqc2010.leeds.ac.uk', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16172',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2009, 'Waterloo', 'Canada', 'CA', false, false, NULL, NULL, 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16171',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2008, 'Tokyo', 'Japan', 'JP', false, false, 'NTT KECL', 'https://web.archive.org/web/20180528173251/http://www.kecl.ntt.co.jp/tqc/2008/index.html', 'https://drops.dagstuhl.de/opus/portals/lipics/index.php?semnr=16170',
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2007, 'Nara', 'Japan', 'JP', false, false, 'NTT KECL', 'https://web.archive.org/web/20170629061934/http://www.kecl.ntt.co.jp/tqc/2007/index.html', NULL,
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system'),
('TQC', 2006, 'Kanagawa', 'Japan', 'JP', false, false, 'NTT KECL', 'https://web.archive.org/web/20170629061833/http://www.kecl.ntt.co.jp/tqc/2006/index.html', NULL,
    NULL, NULL, NULL, NULL, NULL,
    'system', 'system')
ON CONFLICT (venue, year) DO UPDATE SET
    archive_url = EXCLUDED.archive_url,
    archive_organizers_url = EXCLUDED.archive_organizers_url,
    archive_pc_url = EXCLUDED.archive_pc_url,
    archive_steering_url = EXCLUDED.archive_steering_url,
    archive_program_url = EXCLUDED.archive_program_url,
    updated_at = NOW();
